version: '3.8'

services:
  pg-strapi-starter-non-commercial:
    image: postgres
    container_name: pg-strapi-starter-non-commercial
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pg-strapi-starter-non-commercial
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: